stages:
    - checks
    - deploy
    - publish

default:
  tags: [docker]

image: rocker/verse:latest

variables:
  R_LIBS_USER: "$CI_PROJECT_DIR/ci/lib"

cache:
  paths:
    - $R_LIBS_USER

before_script:
  - mkdir -p $R_LIBS_USER
  - echo "R_LIBS='$R_LIBS_USER'" > .Renviron
  - echo "options(repos = c(CRAN = 'https://packagemanager.posit.co/cran/latest'))" >> .Rprofile
  - R -e 'install.packages("pak")'
  - R -e 'pak::local_install_dev_deps()'

test_all:
  stage: checks
  script:
  - R -q -e 'options(error = function() quit(save = "no", status = 1)); testthat::test_local(stop_on_failure = TRUE, stop_on_warning = TRUE)'

run_examples:
  stage: checks
  script:
  - R -q -e 'options(error = function() quit(save = "no", status = 1)); devtools::run_examples(run_donttest = TRUE, run_dontrun = TRUE)'

check:
  stage: checks
  except:
    refs:
      - tags
      - schedules
  script:
  - tlmgr update --self && tlmgr install ec epstopdf-pkg amsmath
  - R -q -e 'remotes::update_packages("rcmdcheck")'
  - R -q -e 'options(error = function() quit(save = "no", status = 1)); rcmdcheck::rcmdcheck(args = "--as-cran", error_on = "warning")'

.github:
  stage: publish
  before_script:
    - git config --global user.email "gitlab@inrae.fr"
    - git config --global user.name "Gitlab CI"
    - git remote add github ${GITHUB_CLONE} || git remote set-url github ${GITHUB_CLONE}
    - git fetch

github_tags:
  extends:
    - .github
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_TAG
  script:
    - git push --force --tags github

increment_dev_version:
  stage: deploy

  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'

  resource_group: main-version-bump

  variables:
    GIT_DEPTH: 0

  before_script: []

  script:
    # Checkout dev branch instead of detached HEAD
    - git checkout -B dev origin/dev

    # Make sure we are up to date
    - git pull --rebase origin dev

    # Increment development version if appropriate
    - Rscript dev/increment_dev_version.R

    # Commit and push only if DESCRIPTION was modified
    - |
      if ! git diff --quiet DESCRIPTION; then
        git config user.name "GitLab CI"
        git config user.email "ci@${CI_SERVER_HOST}"

        git remote set-url origin \
          "https://oauth2:${READ_WRITE_REPO_ACCESS_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"

        git add DESCRIPTION

        NEW_VERSION=$(grep "^Version:" DESCRIPTION | awk '{print $2}')
        git commit -m "chore: bump dev version to v${NEW_VERSION} [skip ci]"

        # Tag and push the new version
        git tag -f "v${NEW_VERSION}"
        git push origin HEAD:refs/heads/dev
        git push -f origin "v${NEW_VERSION}"
      else
        echo "[dev-version] No changes to commit (version unchanged)."
      fi

  allow_failure: false
