stages:
    - checks
    - website

default:
  tags: [docker]

image: rocker/verse:latest

cache:
  paths:
    - "$CI_PROJECT_DIR/ci/lib/"

variables:
  R_LIBS_USER: "$CI_PROJECT_DIR/ci/lib"
  CHECK_DIR: "$CI_PROJECT_DIR/ci/logs"
  BUILD_LOGS_DIR: "$CI_PROJECT_DIR/ci/logs/$CI_PROJECT_NAME.Rcheck"

cache:
  paths:
    - $R_LIBS_USER

before_script:
  - mkdir -p $R_LIBS_USER $BUILD_LOGS_DIR
  - echo "R_LIBS='$R_LIBS_USER'" > .Renviron
  - R -e 'install.packages("rcmdcheck")'
  - R -e 'devtools::install_deps(dep = T)'

.check:
  stage: checks
  script:
    - if [[ $NOT_CRAN == "false" ]]; then sudo apt-get update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended qpdf; fi
    - R -e 'rcmdcheck::rcmdcheck(args = ifelse(as.logical(Sys.getenv("NOT_CRAN")), "--no-manual", "--as-cran"), error_on = "warning")'

check_not_cran:
  variables:
    NOT_CRAN: "true"
  extends: .check

check_as_cran:
  variables:
    NOT_CRAN: "false"
  extends: .check

website:
  stage: website
  only:
    refs:
      - master
      - dev
      - tags
  script:
    - R -e 'remotes::install_gitlab("in-wop/seinebasin", host = "gitlab.irstea.fr")'
    - R -e 'pkgdown::build_site()'
    - sudo apt-get update && sudo apt-get install -y sshpass rsync
    - sshpass -p "${OVH_PASS}" rsync -a -e "ssh -o StrictHostKeyChecking=no" docs/ ${OVH_LOGIN}@${OVH_SFTP}:/home/${OVH_LOGIN}/airgriwrm/
