default:
  tags: [docker]
  image: r-base:latest
  before_script:
    - Rscript -e 'install.packages(c("remotes", "dplyr", "knitr"))'
    - Rscript -e 'remotes::install_gitlab("HYCAR-Hydro/airgr@sd", host = "gitlab.irstea.fr")'
    - R CMD build ../griwrm

check_not_cran:
  variables:
    NOT_CRAN: "true"
  script:
    - R CMD check griwrm_*.tar.gz
