stages:
    - update_packages
    - build
    - checks

default:
  tags: [docker]

image: r-base:latest

cache:
  paths:
    - R_LIBS/

before_script:
  - echo "R_LIBS='$(pwd)/R_LIBS'" > .Renviron

update_packages:
  stage: update_packages
  script:
    - mkdir -p R_LIBS
    - Rscript -e 'if(!dir.exists("R_LIBS/remotes")) install.packages("remotes", lib = "R_LIBS")'
    - apt-get update && apt-get -y install libxml2-dev
    - Rscript -e 'remotes::update_packages(c("dplyr", "rmarkdown", "readr", "lubridate", "zoo", "roxygen2", "DiagrammeR"), lib = "R_LIBS")'
    - Rscript -e 'remotes::install_gitlab("HYCAR-Hydro/airgr@sd", host = "gitlab.irstea.fr", lib = "R_LIBS")'

build:
  stage: build
  script:
    - apt-get update && apt-get -y install libxml2-dev
    - Rscript -e "roxygen2::roxygenise()"
    - R CMD build ../griwrm
  artifacts:
    paths:
      - griwrm_*.tar.gz

check_not_cran:
  stage: checks
  variables:
    NOT_CRAN: "true"
  script:
    - R CMD check --no-manual griwrm_*.tar.gz

check_as_cran:
  stage: checks
  script:
    - R CMD check --as-cran --no-manual griwrm_*.tar.gz
