stages:
    - checks
    - website
    - github

default:
  tags: [docker]

image: rocker/verse:devel

variables:
  R_LIBS_USER: "$CI_PROJECT_DIR/ci/lib"

cache:
  paths:
    - $R_LIBS_USER

before_script:
  - mkdir -p $R_LIBS_USER
  - echo "R_LIBS='$R_LIBS_USER'" > .Renviron
  - R -e 'devtools::install_deps(dep = T)'

test_all:
  stage: checks
  script:
  - R -q -e 'devtools::test()'

check:
  stage: checks
  script:
  - tlmgr update --self && tlmgr install ec epstopdf-pkg
  - R -q -e 'remotes::update_packages("rcmdcheck")'
  - R -q -e 'rcmdcheck::rcmdcheck(args = "--as-cran", error_on = "warning")'

website:
  stage: website
  only:
    refs:
      - master
      - dev
      - tags
  except:
    refs:
      - schedules
  script:
    - R -e 'install.packages("pkgdown")'
    - sed -i 's/`function`/function/g' man/CreateRunOptions.Rd
    - sed -i 's/`function`/function/g' man/CreateCalibOptions.Rd
    - R -e 'remotes::install_gitlab("in-wop/seinebasin", host = "gitlab.irstea.fr")'
    - R -e 'pkgdown::build_site()'
    - sudo apt-get update && sudo apt-get install -y sshpass rsync
    - sshpass -p "${OVH_PASS}" rsync -a -e "ssh -o StrictHostKeyChecking=no" docs/ ${OVH_LOGIN}@${OVH_SFTP}:/home/${OVH_LOGIN}/airgriwrm/

github:
  stage: github
  before_script:
    ##
    ## Install ssh-agent if not already installed, it is required by Docker.
    ## (change apt-get to yum if you use an RPM-based image)
    ##
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'

    ##
    ## Run ssh-agent (inside the build environment)
    ##
    - eval $(ssh-agent -s)

    ##
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    ## We're using tr to fix line endings which makes ed25519 keys work
    ## without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    ##
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

    ##
    ## Create the SSH directory and give it the right permissions
    ##
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    ## Add Github to known hosts (https://stackoverflow.com/a/29380672)
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

    ##
    ## Optionally, if you will be using any Git commands, set the user name and
    ## and email.
    ##
    - git config --global user.email "gitlab@inrae.fr"
    - git config --global user.name "Gitlab CI"
  script:
    - git remote add github git@github.com:inrae/airGRiwrm.git || FAILED=true
    - git remote set-url github git@github.com:inrae/airGRiwrm.git
    - git fetch
    - git push github HEAD:main
    - git push --tags github
