stages:
    - checks
    - website

default:
  tags: [docker]

image: rocker/verse:devel

variables:
  R_LIBS_USER: "$CI_PROJECT_DIR/ci/lib"

cache:
  paths:
    - $R_LIBS_USER

before_script:
  - mkdir -p $R_LIBS_USER
  - echo "R_LIBS='$R_LIBS_USER'" > .Renviron
  - R -e 'devtools::install_deps(dep = T)'

test_all:
  stage: checks
  script:
  - R -q -e 'devtools::test()'

check:
  stage: checks
  script:
  - tlmgr update --self && tlmgr install ec epstopdf-pkg
  - R -q -e 'remotes::update_packages("rcmdcheck")'
  - R -q -e 'rcmdcheck::rcmdcheck(args = "--as-cran", error_on = "warning")'

website:
  stage: website
  only:
    refs:
      - master
      - dev
      - tags
  except:
    refs:
      - schedules
  script:
    - R -e 'install.packages("pkgdown")'
    - sed -i 's/`function`/function/g' man/CreateRunOptions.Rd
    - sed -i 's/`function`/function/g' man/CreateCalibOptions.Rd
    - R -e 'remotes::install_gitlab("in-wop/seinebasin", host = "gitlab.irstea.fr")'
    - R -e 'pkgdown::build_site()'
    - sudo apt-get update && sudo apt-get install -y sshpass rsync
    - sshpass -p "${OVH_PASS}" rsync -a -e "ssh -o StrictHostKeyChecking=no" docs/ ${OVH_LOGIN}@${OVH_SFTP}:/home/${OVH_LOGIN}/airgriwrm/
