stages:
    - checks

default:
  tags: [docker]

image: rocker/tidyverse:3.6.3

cache:
  paths:
    - "$CI_PROJECT_DIR/ci/lib/"

variables:
  R_LIBS_USER: "$CI_PROJECT_DIR/ci/lib"
  CHECK_DIR: "$CI_PROJECT_DIR/ci/logs"
  BUILD_LOGS_DIR: "$CI_PROJECT_DIR/ci/logs/$CI_PROJECT_NAME.Rcheck"

cache:
  paths:
    - $R_LIBS_USER

before_script:
  - mkdir -p $R_LIBS_USER $BUILD_LOGS_DIR
  - echo "R_LIBS='$R_LIBS_USER'" > .Renviron
  - R -e 'install.packages("airGR", repos = "https://cloud.r-project.org/")'
  - R -e 'devtools::install_deps(dep = T)'

.check:
  stage: checks
  script:
    - if [ $AS_CRAN = "true" ]; then sudo apt-get install -y qpdf; fi
    - R -e 'devtools::check(check_dir = Sys.getenv("CHECK_DIR"), cran = !as.logical(Sys.getenv("NOT_CRAN")), env_vars = c(NOT_CRAN = Sys.getenv("NOT_CRAN")))'
    - R -e 'if (length(devtools::check_failures(path = Sys.getenv("BUILD_LOGS_DIR"), note = FALSE)) > 0) stop()'

check_not_cran:
  variables:
    NOT_CRAN: "true"
  extends: .check

check_as_cran:
  variables:
    NOT_CRAN: "false"
  extends: .check
