stages:
    - checks
    - publish

default:
  tags: [docker]

image: rocker/verse:devel

variables:
  R_LIBS_USER: "$CI_PROJECT_DIR/ci/lib"

cache:
  paths:
    - $R_LIBS_USER

before_script:
  - mkdir -p $R_LIBS_USER
  - echo "R_LIBS='$R_LIBS_USER'" > .Renviron
  - R -e 'remotes::install_git("https://gitlab.irstea.fr/HYCAR-Hydro/airgr.git", ref = "dev")'
  - R -e 'devtools::install_deps(dep = T)'

test_all:
  stage: checks
  script:
  - R -q -e 'options(error = function() quit(save = "no", status = 1)); testthat::test_local(stop_on_failure = TRUE, stop_on_warning = TRUE)'

run_examples:
  stage: checks
  script:
  - R -q -e 'options(error = function() quit(save = "no", status = 1)); devtools::run_examples(run_donttest = TRUE, run_dontrun = TRUE)'

check:
  stage: checks
  except:
    refs:
      - tags
      - schedules
  script:
  - sudo apt install tidy
  - tlmgr update --self && tlmgr install ec epstopdf-pkg amsmath
  - R -q -e 'remotes::update_packages("rcmdcheck")'
  - R -q -e 'options(error = function() quit(save = "no", status = 1)); rcmdcheck::rcmdcheck(args = "--as-cran", error_on = "warning")'

.github:
  stage: publish
  except:
    refs:
      - schedules
  before_script:
    - git config --global user.email "gitlab@inrae.fr"
    - git config --global user.name "Gitlab CI"
    - git remote add github ${GITHUB_CLONE} || git remote set-url github ${GITHUB_CLONE}
    - git fetch

github_master_dev:
  extends:
    - .github
  only:
    refs:
      - master
      - dev
  script:
    - git push --force github HEAD:refs/heads/$CI_COMMIT_BRANCH

github_tags:
  extends:
    - .github
  only:
    refs:
      - tags
  script:
    - git push --force --tags github
